name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - name: Update package version
      run: |
          python .github/workflows/add_version.py ${{ github.event.release.tag_name }}
          cat setup.py
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
        
    - name: Commit files
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "${{ secrets.USERNAME }}"
        git add setup.py
        git commit -m "Test Published ${{ github.event.release.tag_name }}"
        git push origin main --force

    
