name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - name: Update package version
      run: |
          python .github/workflows/add_version.py $VERSION
          cat setup.py
      env:
        VERSION: ${GITHUB_REF#refs/tags/}
      
    - name: Version commit
      run: |
          run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git commit -am "Test Package version"
          git push origin main
