name: Publish(Package)

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - name: Update package version
      run: python .github/workflows/add_version.py ${{ github.event.release.tag_name }}
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
        
    - name: Commit files
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "${{ secrets.USERNAME }}"
        git add setup.py
        git commit -m "Release ${{ github.event.release.tag_name }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
    
