# This is a basic workflow to help you get started with Actions
name: Tests
# Controls when the action will run.
on:
  # Triggers the workflow on all branches
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: ["macos-latest"]
        python-version: ['3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Setup conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          use-only-tar-bz2: true
          auto-update-conda: true
          activate-environment: tf-rec

      # Install conda env
      - name : Install conda env
        run: |
          conda install --channel=conda-forge conda-lock
          conda-lock install --name tf-rec conda-lock.yml

      # Activate env
      - name : Activate env
        run : conda activate tf-rec

      # Debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Run Lint and Unit Tests ⚒
        run: |
          pre-commit run --all-files
          python -m unittest discover
