# This is a basic workflow to help you get started with Actions
name: Tests
# Controls when the action will run.
on:
  # Triggers the workflow on all branches
  push:
    branches: '*'
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ['3.8', '3.9']


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-activate-base: true
        run: |
          conda install --channel=conda-forge conda-lock
          conda-lock install --name tf-rec conda-lock.yml
          conda activate tf-rec

      - name: Run Lint and Unit Tests ⚒
        run: |
          pre-commit run --all-files
          python -m unittest discover
